### ISSUE TITLE
Cant install on termux nodejs 20+

### ISSUE THREAD

**Issue by vix3m1** [bajrangCoder/acodex-server#9]
Build error

**Comment by vix3m1** [comment]
nvm, the curl method worked.

**Comment by ras-drive** [comment]
I also got the curl method working, for anyone wondering it can be found here: https://github.com/bajrangCoder/acode-plugin-acodex#installation

**Comment by ras-drive** [comment]
Or you can run a command to get it to work with the regular PKG build system: ```cd $HOME && mkdir -p .gyp && echo "{'variables': {'android_ndk_path': ''}}" > .gyp/include.gypi```
